//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.27 at 04:23:22 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.server.contacts.dia.ru/")
package ru.dia.contacts.server.ws;
